dist: xenial
language: cpp
os: linux
env: 
- QT_BASE=512 VER=6.0 STDFLAGS="-std=c++11 -std=c++14 -std=c++17" BUILD_TYPE=Release
addons:
  sonarcloud:
    organization: nouname-github
before_install:
  - pip install --user cpp-coveralls
  - if [ "$QT_BASE" = "512" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y; fi
  - sudo apt-get update -qq
install:
  - sudo apt-get install libgl1-mesa-dev
  - if [ "$QT_BASE" = "512" ]; then sudo apt-get install qt512webengine ; source /opt/qt512/bin/qt512-env.sh ; export QTHOME=/opt/qt512 ; fi
script:
    - export QT_QPA_PLATFORM=offscreen
    - qmake
    - make
    # Auto-auth
    - "./util/util" 
    # Tests
    - "./l8-test/l8-test"
after_success:
- coveralls --root . -E ".*external.*" -E ".*tests.*"
- build-wrapper-linux-x86-64 --out-dir bw-output make clean all
- sonar-scanner -D"sonar.projectKey=nouname_lastlab" -D"sonar.organization=nouname-github" -D"sonar.sources=." -D"sonar.cfamily.build-wrapper-output=bw-output" -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=88d4640d0b98b73a568146a9621545c047af52ba"
    
