QT.webenginecore_private.VERSION = 5.12.2
QT.webenginecore_private.name = QtWebEngineCore
QT.webenginecore_private.module =
QT.webenginecore_private.libs = $$QT_MODULE_LIB_BASE
QT.webenginecore_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWebEngineCore/5.12.2 $$QT_MODULE_INCLUDE_BASE/QtWebEngineCore/5.12.2/QtWebEngineCore
QT.webenginecore_private.frameworks =
QT.webenginecore_private.depends = webenginecore
QT.webenginecore_private.uses =
QT.webenginecore_private.module_config = v2 internal_module
QT.webenginecore_private.enabled_features = webengine-alsa webengine-bison webengine-flex webengine-gperf webengine-host-pkg-config webengine-pepper-plugins webengine-printing-and-pdf webengine-proprietary-codecs webengine-pulseaudio webengine-python2 webengine-system-dbus webengine-system-opus webengine-system-libwebp webengine-system-ffmpeg webengine-system-fontconfig webengine-system-freetype webengine-system-glib webengine-system-glibc webengine-system-harfbuzz webengine-system-icu webengine-system-jpeg webengine-system-jsoncpp webengine-system-khr webengine-system-lcms2 webengine-system-libdrm webengine-system-libevent webengine-system-libxml2 webengine-system-minizip webengine-system-ninja webengine-system-nss webengine-system-png webengine-system-protobuf webengine-system-re2 webengine-system-snappy webengine-system-x11 webengine-system-xcomposite webengine-system-xcursor webengine-system-xi webengine-system-xtst webengine-system-zlib webengine-testsupport webengine-ui-delegates webengine-v8-snapshot webengine-v8-snapshot-support webengine-webrtc
QT.webenginecore_private.disabled_features = webengine-embedded-build webengine-arm-thumb webengine-kerberos webengine-poppler-cpp webengine-sanitizer webengine-system-gn webengine-system-libvpx webengine-win-compiler64 webengine-winversion
QMAKE_LIBS_PULSEAUDIO = /usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so /usr/lib/x86_64-linux-gnu/libpulse.so /usr/lib/x86_64-linux-gnu/libglib-2.0.so
QMAKE_INCDIR_PULSEAUDIO = /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include
QMAKE_LIBS_WEBENGINE_DBUS = /usr/lib/x86_64-linux-gnu/libdbus-1.so
QMAKE_INCDIR_WEBENGINE_DBUS = /usr/include/dbus-1.0 /usr/lib/x86_64-linux-gnu/dbus-1.0/include
QMAKE_LIBS_WEBENGINE_FFMPEG = /usr/lib/x86_64-linux-gnu/libavcodec.so /usr/lib/x86_64-linux-gnu/libavformat.so /usr/lib/x86_64-linux-gnu/libavutil.so
QMAKE_LIBS_WEBENGINE_OPUS = /usr/lib/x86_64-linux-gnu/libopus.so
QMAKE_INCDIR_WEBENGINE_OPUS = /usr/include/opus
QMAKE_LIBS_WEBENGINE_WEBP = /usr/lib/x86_64-linux-gnu/libwebpmux.so /usr/lib/x86_64-linux-gnu/libwebpdemux.so /usr/lib/x86_64-linux-gnu/libwebp.so
QMAKE_LIBS_WEBENGINE_FONTCONFIG = /usr/lib/x86_64-linux-gnu/libfontconfig.so /usr/lib/x86_64-linux-gnu/libfreetype.so
QMAKE_INCDIR_WEBENGINE_FONTCONFIG = /usr/include/uuid /usr/include/freetype2 /usr/include/libpng16
QMAKE_LIBS_WEBENGINE_FREETYPE = /usr/lib/x86_64-linux-gnu/libfreetype.so
QMAKE_INCDIR_WEBENGINE_FREETYPE = /usr/include/freetype2 /usr/include/libpng16
QMAKE_LIBS_WEBENGINE_GLIB = /usr/lib/x86_64-linux-gnu/libglib-2.0.so
QMAKE_INCDIR_WEBENGINE_GLIB = /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include
QMAKE_LIBS_WEBENGINE_HARFBUZZ = /usr/lib/x86_64-linux-gnu/libharfbuzz.so
QMAKE_INCDIR_WEBENGINE_HARFBUZZ = /usr/include/harfbuzz /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include
QMAKE_LIBS_WEBENGINE_ICU = /usr/lib/x86_64-linux-gnu/libicui18n.so /usr/lib/x86_64-linux-gnu/libicuuc.so /usr/lib/x86_64-linux-gnu/libicudata.so
QMAKE_LIBS_WEBENGINE_JPEGLIB = /usr/lib/x86_64-linux-gnu/libjpeg.so
QMAKE_LIBS_WEBENGINE_JSONCPP = /usr/lib/x86_64-linux-gnu/libjsoncpp.so
QMAKE_INCDIR_WEBENGINE_JSONCPP = /usr/include/jsoncpp
QMAKE_LIBS_WEBENGINE_LCMS2 = /usr/lib/x86_64-linux-gnu/liblcms2.so
QMAKE_LIBS_WEBENGINE_LIBDRM = /usr/lib/x86_64-linux-gnu/libdrm.so
QMAKE_INCDIR_WEBENGINE_LIBDRM = /usr/include/libdrm
QMAKE_LIBS_WEBENGINE_LIBEVENT = /usr/lib/x86_64-linux-gnu/libevent.so
QMAKE_LIBS_WEBENGINE_LIBXML2 = /usr/lib/x86_64-linux-gnu/libxslt.so /usr/lib/x86_64-linux-gnu/libxml2.so
QMAKE_INCDIR_WEBENGINE_LIBXML2 = /usr/include/libxml2
QMAKE_LIBS_WEBENGINE_MINIZIP = /usr/lib/x86_64-linux-gnu/libminizip.so
QMAKE_INCDIR_WEBENGINE_MINIZIP = /usr/include/minizip
QMAKE_LIBS_WEBENGINE_NSS = /usr/lib/x86_64-linux-gnu/libnss3.so /usr/lib/x86_64-linux-gnu/libnssutil3.so /usr/lib/x86_64-linux-gnu/libsmime3.so /usr/lib/x86_64-linux-gnu/libssl3.so /usr/lib/x86_64-linux-gnu/libplds4.so /usr/lib/x86_64-linux-gnu/libplc4.so /usr/lib/x86_64-linux-gnu/libnspr4.so
QMAKE_INCDIR_WEBENGINE_NSS = /usr/include/nss /usr/include/nspr
QMAKE_LIBS_WEBENGINE_PNG = /usr/lib/x86_64-linux-gnu/libpng16.so /usr/lib/x86_64-linux-gnu/libz.so
QMAKE_INCDIR_WEBENGINE_PNG = /usr/include/libpng16
QMAKE_LIBS_WEBENGINE_PROTOBUF = /usr/lib/x86_64-linux-gnu/libprotobuf.so
QMAKE_LIBS_WEBENGINE_X11 = /usr/lib/x86_64-linux-gnu/libX11.so
QMAKE_LIBS_WEBENGINE_XCOMPOSITE = /usr/lib/x86_64-linux-gnu/libXcomposite.so
QMAKE_LIBS_WEBENGINE_XCURSOR = /usr/lib/x86_64-linux-gnu/libXcursor.so
QMAKE_LIBS_WEBENGINE_XI = /usr/lib/x86_64-linux-gnu/libXi.so
QMAKE_LIBS_WEBENGINE_XTST = /usr/lib/x86_64-linux-gnu/libXtst.so
QMAKE_LIBS_WEBENGINE_ZLIB = /usr/lib/x86_64-linux-gnu/libz.so
